/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/iron_man/ironman.gltf 
*/

import React, { useRef } from 'react'
import { useFBX, useGLTF } from '@react-three/drei'

const Ironman = (props) => {
    const { nodes, materials } = useGLTF('./iron_man/ironman.gltf');
    const {animations: JabCross} = useFBX("./iron_man/animations/Jab Cross.fbx");
    const {animations: JumpingDown} = useFBX("./iron_man/animations/Jumping Down.fbx");
    const {animations: CrouchToStand} = useFBX("./iron_man/animations/Crouch To Stand.fbx");
    const {animations: SillyDancing} = useFBX("./iron_man/animations/Silly Dancing.fbx");

    JabCross[0].name = "JabCross";
    JumpingDown[0].name = "JumpingDown";
    CrouchToStand[0].name = "CrouchToStand";
    SillyDancing[0].name = "SillyDancing";

    return (
        <group {...props} dispose={null}>
            <group rotation={[ 4.5, -0.07, 0.35]}>
                <mesh geometry={nodes.Object_2.geometry} material={materials['default']} scale={0.0008} />
                <mesh geometry={nodes.Object_3.geometry} material={materials['default']} scale={0.0008} />
                <mesh geometry={nodes.Object_4.geometry} material={materials['default']} scale={0.0008} />
            </group>
        </group>
    )
}

export default Ironman;

useGLTF.preload('./iron_man/ironman.gltf');
