/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/iron_man/scene.gltf 
Author: GrandFX (https://sketchfab.com/grandFX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-man-69dde1ad49e94852984e3d83928efd65
Title: Iron Man
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Scene = (props) => {
  const { nodes, materials } = useGLTF('./iron_man/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['default']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['default']} />
      </group>
    </group>
  )
}

export default Scene;

useGLTF.preload('./iron_man/scene.gltf');
